version: '3'

services:
  aws-study-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5019:5019"
    volumes:
      # This allows the questions.json file to persist between container restarts
      - ./questions.json:/app/questions.json
    restart: unless-stopped
